# Generated by Django 5.2.11 on 2026-02-27 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Symptom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pain", "Pain & Discomfort"),
                            ("physical", "Physical"),
                            ("emotional", "Emotional"),
                            ("digestive", "Digestive"),
                            ("skin", "Skin & Hair"),
                            ("sleep", "Sleep"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Font Awesome icon class", max_length=50
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="CyclePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("predicted_start", models.DateField()),
                ("predicted_end", models.DateField()),
                ("predicted_ovulation", models.DateField(blank=True, null=True)),
                ("fertile_window_start", models.DateField(blank=True, null=True)),
                ("fertile_window_end", models.DateField(blank=True, null=True)),
                (
                    "confidence_score",
                    models.FloatField(default=0.0, help_text="0.0 to 1.0"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycle_predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["predicted_start"],
            },
        ),
        migrations.CreateModel(
            name="ReminderPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "days_before_period",
                    models.IntegerField(
                        default=3,
                        help_text="Days before predicted period to send reminder",
                    ),
                ),
                ("remind_via_email", models.BooleanField(default=True)),
                (
                    "daily_log_reminder",
                    models.BooleanField(
                        default=True, help_text="Remind to log daily symptoms"
                    ),
                ),
                (
                    "daily_reminder_time",
                    models.TimeField(
                        default="20:00", help_text="What time to send daily reminder"
                    ),
                ),
                (
                    "pain_tips_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Receive personalized pain management tips",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_prefs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CycleLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start_date", models.DateField()),
                ("period_end_date", models.DateField(blank=True, null=True)),
                (
                    "cycle_length",
                    models.IntegerField(
                        blank=True,
                        help_text="Days from this period start to next period start",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycle_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start_date"],
                "unique_together": {("user", "period_start_date")},
            },
        ),
        migrations.CreateModel(
            name="PainRemedy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("medication", "Medication"),
                            ("heat", "Heat Therapy"),
                            ("exercise", "Exercise / Movement"),
                            ("rest", "Rest"),
                            ("nutrition", "Nutrition / Diet"),
                            ("herbal", "Herbal / Natural"),
                            ("massage", "Massage"),
                            ("breathing", "Breathing / Meditation"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("times_used", models.IntegerField(default=0)),
                ("total_effectiveness", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pain_remedies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pain Remedies",
                "ordering": ["-times_used"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="PartnerShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "share_level",
                    models.CharField(
                        choices=[
                            ("dates_only", "Period Dates Only"),
                            ("dates_symptoms", "Dates + General Symptoms"),
                            ("everything", "Full Details"),
                        ],
                        default="dates_only",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "partner")},
            },
        ),
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "pain_level",
                    models.IntegerField(
                        choices=[
                            (0, "0"),
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                        ],
                        default=0,
                        help_text="Pain level from 0 (none) to 10 (severe)",
                    ),
                ),
                (
                    "pain_locations",
                    models.JSONField(
                        blank=True, default=list, help_text="List of pain location keys"
                    ),
                ),
                (
                    "flow_level",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("spotting", "Spotting"),
                            ("light", "Light"),
                            ("medium", "Medium"),
                            ("heavy", "Heavy"),
                            ("very_heavy", "Very Heavy"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "mood",
                    models.IntegerField(
                        choices=[
                            (1, "Very Low"),
                            (2, "Low"),
                            (3, "Okay"),
                            (4, "Good"),
                            (5, "Great"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "energy",
                    models.IntegerField(
                        choices=[
                            (1, "Exhausted"),
                            (2, "Low Energy"),
                            (3, "Normal"),
                            (4, "Energized"),
                            (5, "Very Energized"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Basal body temperature in Fahrenheit",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Weight in lbs",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "water_intake",
                    models.IntegerField(default=0, help_text="Glasses of water"),
                ),
                (
                    "sleep_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Hours of sleep",
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "exercise_minutes",
                    models.IntegerField(default=0, help_text="Minutes of exercise"),
                ),
                (
                    "pain_remedies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of remedies tried today",
                    ),
                ),
                (
                    "remedy_effectiveness",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        help_text="How effective were your remedies? 1-5",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "symptoms",
                    models.ManyToManyField(
                        blank=True, related_name="daily_logs", to="App_Tracker.symptom"
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
