# Generated by Django 5.2.11 on 2026-02-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LifestyleTip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("menstrual", "Menstrual Phase"),
                            ("follicular", "Follicular Phase"),
                            ("ovulation", "Ovulation Phase"),
                            ("luteal", "Luteal Phase"),
                            ("all", "All Phases"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pain_relief", "Pain Relief"),
                            ("exercise", "Exercise & Movement"),
                            ("nutrition", "Nutrition"),
                            ("self_care", "Self Care"),
                            ("sleep", "Sleep"),
                            ("mental_health", "Mental Health"),
                            ("work_life", "Work & Productivity"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="fas fa-heart", max_length=50)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["phase", "order"],
            },
        ),
    ]
