# Generated by Django 5.2.11 on 2026-02-27 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="fas fa-heart", max_length=50)),
                ("color", models.CharField(default="#e74c3c", max_length=7)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Story Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AnonymousStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anonymous_name",
                    models.CharField(
                        default="Anonymous",
                        help_text="Display name (anonymous by default)",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=264)),
                ("slug", models.SlugField(max_length=300, unique=True)),
                ("content", models.TextField()),
                (
                    "age_at_experience",
                    models.IntegerField(
                        blank=True,
                        help_text="Your age when this happened (optional)",
                        null=True,
                    ),
                ),
                ("me_too_count", models.IntegerField(default=0)),
                ("support_count", models.IntegerField(default=0)),
                ("is_approved", models.BooleanField(default=True)),
                ("is_reported", models.BooleanField(default=False)),
                ("report_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anonymous_stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to="App_Community.storycategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Anonymous Stories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoryComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anonymous_name",
                    models.CharField(default="Anonymous", max_length=50),
                ),
                ("content", models.TextField(max_length=2000)),
                ("is_approved", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="App_Community.anonymousstory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoryReaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[("me_too", "Me Too"), ("support", "Sending Support")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="App_Community.anonymousstory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="story_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("story", "user", "reaction_type")},
            },
        ),
    ]
